feat(BUILD-1512): sbom plugin
SonarSource/sonar-dummy-oss pull request #66
Opened 2022-04-12 09:50 UTC by julien-carsique-sonarsource

BUILD-1512: generate SBOM

Add Gradle plugin

2022-04-12 11:45 UTC, tomverin approved these changes

2022-04-12 13:29 UTC, tomverin requested changes
There's no bom in the build 258 https://repox.jfrog.io/ui/builds/sonar-dummy-oss/258/1649757082885/published/org.sonarsource.dummy:sonar-dummy-oss-plugin:2.5.0.258?buildRepo=artifactory-build-info

2022-04-12 17:46 UTC, julien-carsique-sonarsource commented
```
Deploying artifact: HIDDEN-BY-CIRRUS-CI/sonarsource-public-qa/org/sonarsource/dummy/sonar-dummy-oss-plugin/2.5.0.260/sonar-dummy-oss-plugin-2.5.0.260-cyclonedx.json
```
And the file is there https://repox.jfrog.io/ui/builds/sonar-scanner-cli/2775/1649755371688/published/org.sonarsource.scanner.cli:sonar-scanner-cli:4.8.0.2775?buildRepo=artifactory-build-info

2022-04-13 06:58 UTC, tomverin approved these changes

2022-04-13 07:03 UTC, malena-ebert-sonarsource requested changes, later dismissed

2022-04-13 07:03 UTC, malena-ebert-sonarsource commented on build.gradle
> +      mavenJava(MavenPublication) {
rename `mavenJava` to `cyclonedxBom`

2022-04-13 13:40 UTC, julien-carsique-sonarsource commented on build.gradle
> +      mavenJava(MavenPublication) {
it's the default and required by artifactoryPublish

2022-04-13 13:40 UTC, merged